-- Patient Portal: new audit event types
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'FEEDBACK_CREATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'APPOINTMENT_CANCELLED_BY_PATIENT';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'DOCUMENT_UPLOADED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'PATIENT_PROFILE_UPDATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'PATIENT_ACCOUNT_LINKED';
