import { alert } from '@/lib/styles'

export function AiDisclaimer() {
  return (
    <div role="note" className={`${alert.warning} mb-6`}>
      <p className="text-sm font-semibold text-warning-800">AI-Assisted Suggestions Only</p>
      <p className="mt-1 text-sm text-warning-700">
        All suggestions are generated by an AI model and must be reviewed by a qualified clinician.
        Clinical judgment is always required. Do not rely solely on AI output for patient care decisions.
      </p>
    </div>
  )
}
